# Lab 5 

In [74]:
from pylab import *

## 5.1 Basic list and array operations

### 1)
Create a vector that has the elements: 6, 8*3, 2.5, ‘labtime’, and √2.

> *In general for this lab, don’t just create vectors, but also print out their contents for verification.*

In [75]:
vec = [6, 8*3, 2.5, 'labtime', sqrt(2)]
print(array(vec))

['6' '24' '2.5' 'labtime' '1.4142135623730951']


### 2) 
Create a vector in which the first element is 0, and the last element is 42,
with an increment of 3 between the elements (0, 3, 6, . . . . . . , 42).

> *Starting with this question, create elements using “shortcut” techniques such as the colon operator, rather than manual entry of all the values.*

In [76]:
vec = list(range(0,43, 3))
print(array(vec))

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42]


### 3) 
Create a vector in which the first element is 18, the elements decrease with increments of −4.5, and the last element is −18.

In [77]:
vec = arange(18, -19, -4.5)
print(vec)

[ 18.   13.5   9.    4.5   0.   -4.5  -9.  -13.5 -18. ]


### 4)
Create a list with 16 equally spaced elements in which the first element is 5 and the last element is 61.

In [78]:
vec = linspace(5, 61, 16) 
list(vec)

[5.0,
 8.733333333333334,
 12.466666666666667,
 16.2,
 19.933333333333334,
 23.666666666666668,
 27.4,
 31.133333333333333,
 34.86666666666667,
 38.6,
 42.333333333333336,
 46.06666666666667,
 49.8,
 53.53333333333333,
 57.266666666666666,
 61.0]

### 5) 

a) Create two character strings, ‘*name1*’ and ‘*name2*’, containing your first and last names.

b) Create a third string variable by concatenating the first two strings, along with an appropriate space.

In [79]:
# Method 1 using list comprehension
name1 = ['A','n','d','r','y']
name2 = ['P','a','e','z']
fullName = ''.join([name1[i] for i in range(len(name1))]) + ' ' + ''.join([name2[i] for i in range(len(name2))])
print(fullName)

Andry Paez


In [80]:
# Method 2 using numpy
name1 = 'Andry'
name2 = 'Paez'
fullName = array([name1, name2])
fullName = char.add(char.add(fullName[0], ' '), fullName[1])
print(fullName)


Andry Paez


In [81]:
# Method 3 using string concatenation
name1 = 'Andry'
name2 = 'Paez'
fullName = name1 + ' ' + name2
print(fullName)

Andry Paez


### 6)

a) Create a vector, named `Afirst`, that has 13 elements in which the first is 3, the increment is 4 and the last element is 51.

b) Create a new vector, named `Asecond`, that has seven elements (do this step first.) 

The first four elements of `Asecond` are the first four elements of the vector `Afirst` and the last three elements of `Asecond` are the last three elements of the vector `Afirst`.

In [82]:
Afirst = arange(3, 52, 4)
print(Afirst)

[ 3  7 11 15 19 23 27 31 35 39 43 47 51]


In [83]:
Asecond = [i for i in range(7)]
print(Asecond)
Asecond[:4], Asecond[-3:] = Afirst[:4], Afirst[-3:]
print(Asecond)

[0, 1, 2, 3, 4, 5, 6]
[3, 7, 11, 15, 43, 47, 51]


## 5.2 More vectors, 2D arrays, and vectorization

### 1) 
Create an array w with values `0, 0.1, 0.2, ..., 3`.

Print the following: `w[:], w[:−2], w[::5], w[2:−2:6]`.

Explain in each case the elements of the array that are being printed.


In [84]:
w = arange(0, 3.1, 0.1)
print(w)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3. ]


In [85]:
print(w[:])

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3. ]


```python
print(w[:])
``` 
is using slicing notation to print all elements of the variable `w`

In [86]:
print(w[:-2])

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8]


```python
print(w[:-2])
```
is using slicing to print all elements except the last two

In [87]:
print(w[::5])

[0.  0.5 1.  1.5 2.  2.5 3. ]


```python 
print(w[::5])
```
is using slicing to extract every 5th character from the string `w` and then printing the result.

In [88]:
print(w[2:-2:6])

[0.2 0.8 1.4 2.  2.6]


```python 
print(w[2:-2:6])
```
is slicing the array from the second element to the second to last element, dividing by 6 (step of 6) then printing


### 2)

Create a 5-element vector, and a 2 × 3 array, with names and values of your choosing. 

Inspect their properties using `type()`, `whos`, `len()`, `shape()`, and `size()`.

Report the results and comment on what they mean.

In [89]:
vec = [x**2 for x in range(5)]
vec = array(vec)

arr = [[x**2 for x in range(3)]for i in range(2)]
arr

def printSquareArray(arr):
    for row in range(len(arr)):
        for col in range(len(arr[row])):
            print(arr[row][col], end=' ')
        print()

print(f'Vector: {vec}')
print('Array: ')
printSquareArray(arr)

Vector: [ 0  1  4  9 16]
Array: 
0 1 4 
0 1 4 


In [90]:
print(f'The data type of the 5-element vector is {type(vec)}')
print(f'The data type of the 2x3 array is {type(arr)}')

The data type of the 5-element vector is <class 'numpy.ndarray'>
The data type of the 2x3 array is <class 'list'>


In [121]:
# prints the variables in the workspace that are of type list
%whos list

Variable   Type    Data/Info
----------------------------
Asecond    list    n=7
arr        list    n=2


In [122]:
# prints the variables in the workspace that are numpy arrays
%whos ndarray

Variable   Type       Data/Info
-------------------------------
Afirst     ndarray    13: 13 elems, type `int64`, 104 bytes
vec        ndarray    5: 5 elems, type `float64`, 40 bytes
w          ndarray    31: 31 elems, type `float64`, 248 bytes


In [124]:
print(f'The length of the vector is {len(vec)}') # returns the length of the vector
print(f'The length of the array is {len(arr)}') # returns the length of the array

The length of the vector is 5
The length of the array is 2


In [128]:
# format (rows, columns)
print(f'The dimensions of the vector is {shape(vec)}') # returns the shape/dimensions of the vector
print(f'The dimensions of the array is {shape(arr)}') # returns the shape/dimensions of the array

The dimensions of the vector is (5,)
The dimensions of the array is (2, 3)


In [144]:
# print out the number of elements given an axis of the vector and array
print(f'The number of columns in the vector is {size(vec, 0)}') # returns the number of columns in the vector
print(f'The number of rows in the array is {size(arr, 0)}') # returns the number of rows in the array

The number of columns in the vector is 5
The number of rows in the array is 2


### 3) 
Create a vector, try the following built-in functions on it, and comment on what they do:

```python
len(), min(), max(), sum(), sorted(), sort()
```

In [92]:
vec = linspace(0, 16, 5)
shuffle(vec)
print(vec)

[ 0. 16. 12.  4.  8.]


In [93]:
len(vec) #prints the length of the vector

5

In [94]:
min(vec) #prints the minimum value of the vector

0.0

In [95]:
max(vec) #prints the maximum value of the vector

16.0

In [96]:
sum(vec) #prints the sum of the vector

40.0

In [97]:
sorted(vec) #sort the vector in ascending order by creating a new vector with the sorted version of the original vector

[0.0, 4.0, 8.0, 12.0, 16.0]

In [98]:
sort(vec) #sort the vector in ascending order by modifying the given vector

array([ 0.,  4.,  8., 12., 16.])

### 4) 

Create a vector names `same` with eleven elements that are all `4`

In [153]:
same = [4 for x in range(11)] # using list comprehension
same = array(same)
print(f'The vector is {same} and its size is {size(same)}')

The vector is [4 4 4 4 4 4 4 4 4 4 4] and its size is 11


### 5) 
Create the matrix shown below by using vector notation for creating vectors with constant spacing and/or the linspace command when entering the rows.

(Do not worry if the number formatting is different from what is shown here.)

![image](lab5.jpg)

In [215]:
B = [arange(0, 29, 4), arange(69, 61, -1), arange(1.4, -0.8, -0.3)]
B

[array([ 0,  4,  8, 12, 16, 20, 24, 28]),
 array([69, 68, 67, 66, 65, 64, 63, 62]),
 array([ 1.4,  1.1,  0.8,  0.5,  0.2, -0.1, -0.4, -0.7])]

### 6)
Replace the fourth column in matrix `B` with the numbers 1->3

In [216]:
# Brute force method 
B[0][3], B[1][3], B[2][3] = 1, 2, 3
B



[array([ 0,  4,  8,  1, 16, 20, 24, 28]),
 array([69, 68, 67,  2, 65, 64, 63, 62]),
 array([ 1.4,  1.1,  0.8,  3. ,  0.2, -0.1, -0.4, -0.7])]

### 7)
a) Using the colon operator, create a 2×5 matrix, named `msame` in which all the elements are the number 7.

In [291]:
# create a nump array with 2 dimensions
msame = zeros((2, 5))
msame[:5, :5] = 7
msame

array([[7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.]])

b) Add a third row of zeros, and then a fourth row with the numbers 1 to 5.

In [292]:
msame = vstack((msame, [0 for i in range(5)]))
msame = vstack((msame, [i+1 for i in range(5)]))
msame

array([[7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [0., 0., 0., 0., 0.],
       [1., 2., 3., 4., 5.]])

c) Add a fifth row that multiplies the second row by the number 6.

In [293]:
msame = vstack((msame, [i*6 for i in msame[1]]))
msame

array([[ 7.,  7.,  7.,  7.,  7.],
       [ 7.,  7.,  7.,  7.,  7.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  2.,  3.,  4.,  5.],
       [42., 42., 42., 42., 42.]])

d) Concatenate (= combine horizontally) the matrix B above with the middle
three rows of `msame`.

In [294]:
# Concatenate (= combine horizontally) the matrix B above with the middle
msameNew = concatenate((array(B), msame[1:4]), axis=1)
print(msameNew)

[[ 0.   4.   8.   1.  16.  20.  24.  28.   7.   7.   7.   7.   7. ]
 [69.  68.  67.   2.  65.  64.  63.  62.   0.   0.   0.   0.   0. ]
 [ 1.4  1.1  0.8  3.   0.2 -0.1 -0.4 -0.7  1.   2.   3.   4.   5. ]]


### 8)
Evaluate the dot product of two vectors, using vectorization to do so in just one line of code

In [299]:
u = array([1, 4, 1])
v = array([2, 1, 3])
# dot product using vectors
sum(u*v)

9