# Python Lists

"Lists" are 1D containers of elements that are easy to manipulate and allow for various data types:


In [58]:
from pylab import * #Import numpy + plotting

In [59]:
#Use square brackets [] and commas to separate elements
a = [1, 2.0, 'sjsu'] #A list 'a' storing an int, a float, and a string
b=list(range(1,11)) #range(start, stop)
c=list(range(1,11,2)) #range(start, stop, step)
d=[] #an empty list waiting to be filled

In [60]:
a

[1, 2.0, 'sjsu']

In [61]:
b

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [62]:
c

[1, 3, 5, 7, 9]

In [63]:
d

[]

List operations

In [64]:
e=a+c
e

[1, 2.0, 'sjsu', 1, 3, 5, 7, 9]

In [65]:
f=2*a
f

[1, 2.0, 'sjsu', 1, 2.0, 'sjsu']

In [66]:
a.append('Q')
a

[1, 2.0, 'sjsu', 'Q']

In [67]:
a1, a2, a3, a4 = a #unpack

In [68]:
a1

1

In [69]:
a2

2.0

In [70]:
a3

'sjsu'

In [71]:
a4

'Q'

# Accessing Elements

Indices in Python start with 0, ‘:’ indicates a range, ‘−’ sign counts backward

In [72]:
b

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [73]:
b[0]

1

In [74]:
b[1:3] #'slicing' into a sublist

[2, 3]

In [75]:
b[1:8:2] #last number specifies step

[2, 4, 6, 8]

In [76]:
b[-1]

10

In [77]:
b.index(4) #find index of element value

3

Changing Elements:

In [78]:
b[2]=5
b

[1, 2, 5, 4, 5, 6, 7, 8, 9, 10]

In [79]:
b[3:7]=b[4:8] #rearrange elements
b

[1, 2, 5, 5, 6, 7, 8, 8, 9, 10]

In [80]:
b.insert(2,'X')
b

[1, 2, 'X', 5, 5, 6, 7, 8, 8, 9, 10]

In [81]:
del b[2]
b

[1, 2, 5, 5, 6, 7, 8, 8, 9, 10]

# NumPy Arrays

NumPy package extension to Python, permits efficient and simple vectorized math

(factors of ~100−1000 faster than lists!)

In [82]:
A = array([1.,2,3,4,5])
A

array([1., 2., 3., 4., 5.])

In [83]:
B = arange(1.0,11.0,2.0) #(start, stop, step)
B

array([1., 3., 5., 7., 9.])

In [84]:
C = linspace(1.,10.,10) #(start, stop, N_elements)
C

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [85]:
D = array([])
D

array([], dtype=float64)

# Accessing Array Elements

In [86]:
B[1:]=B[:-1]
B

array([1., 1., 3., 5., 7.])

Change elements:

In [87]:
H = append(A,6.0)
H

array([1., 2., 3., 4., 5., 6.])

In [88]:
I = insert(B,3,44.0) #(array, index, value)
I

array([ 1.,  1.,  3., 44.,  5.,  7.])

In [89]:
J = delete(I,3)
J

array([1., 1., 3., 5., 7.])

In [90]:
J[:] = 5.0
J

array([5., 5., 5., 5., 5.])

# Additional Ways to Create Arrays

In [91]:
K=zeros(5)
K

array([0., 0., 0., 0., 0.])

In [92]:
L=ones(4)
L

array([1., 1., 1., 1.])

In [93]:
B2=array(b) #Convert a list to an array
B2

array([ 1,  2,  5,  5,  6,  7,  8,  8,  9, 10])

In [94]:
B3=B2*0 + 123.0 #Shortcut for new array, same size
B3

array([123., 123., 123., 123., 123., 123., 123., 123., 123., 123.])

# Lists vs. Arrays

Lists:

* Holds arbitrary variable types
* Easier to Add and remove elements

Arrays:

* Efficient for math operations
* Element by element operations

In [95]:
b = list(range(1,11))
b

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [96]:
B=arange(1.0,11.0)
B

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [97]:
b2 = b  #list 
b[0] = 0
b2  

[0, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [98]:
b2=b[:] #list
b[0]=-1
b2

[0, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [99]:
B2=B  #array
B[0]=0.0
B2

array([ 0.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [100]:
B2=copy(B)  #array
B[0]=-1.0
B2

array([ 0.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

# List and Array Analysis Operations

In [101]:
len(b)

10

In [102]:
min(b)

-1

In [103]:
max(b)

10

In [104]:
sum(b)

53

In [105]:
sorted(b) #list output

[-1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [106]:
sort(b) #array output

array([-1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Math Operations on Vectors

What are weights of different animals on the Moon?

In [107]:
m_cow = 500 #kg
m_whale = 100000 #kg
m_dinosaur = 5000 #kg
m = array([m_cow, m_whale, m_dinosaur])
g_Moon= 1.62 #m/s^2
Weight = m*g_Moon #in Newtons (kg*m/s^2)
Weight

array([   810., 162000.,   8100.])

Mathematical Operations on Arrays: Applied to each element

In [108]:
2.0*A

array([ 2.,  4.,  6.,  8., 10.])

In [109]:
B**3

array([  -1.,    8.,   27.,   64.,  125.,  216.,  343.,  512.,  729.,
       1000.])

In [110]:
C = A + B
C

ValueError: operands could not be broadcast together with shapes (5,) (10,) 

In [54]:
D = A * B
D

ValueError: operands could not be broadcast together with shapes (5,) (10,) 

We get errors for the last two operations because arrays A and B must be the same size, but aren't.

In [55]:
sin(B)

array([-0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [56]:
sqrt(B)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([       nan, 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

Note that the first element, sqrt(-1), is undefined since it is an imaginary number.

# N-dimensional Arrays

In [112]:
M = array([[1.,2.],[3.,4.]]) #A 2D matrix, rows are in inner set of [], can do N dimensions
M

array([[1., 2.],
       [3., 4.]])

In [113]:
N = array([[1.,2.,3.]])  #a matrix with 1 row
N

array([[1., 2., 3.]])

In [114]:
O = hstack((M,[[5.],[6.]]))  #add a column
O

array([[1., 2., 5.],
       [3., 4., 6.]])

In [115]:
P = vstack((N,[4.,5.,6.])) #add a row
P

array([[1., 2., 3.],
       [4., 5., 6.]])

In [116]:
Q = concatenate((M,M))
Q

array([[1., 2.],
       [3., 4.],
       [1., 2.],
       [3., 4.]])

In [117]:
help(concatenate)

Help on function concatenate in module numpy:

concatenate(...)
    concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
        provided together with `out`.
    
        .. versionadded:: 1.20.0
    
    casting : {'no', 'equiv', 'safe', '

In [118]:
M[0,1] = -1.0
M

array([[ 1., -1.],
       [ 3.,  4.]])

In [119]:
M[-1] #show last row

array([3., 4.])

In [121]:
M[:,0] #show first column

array([1., 3.])